language: go

sudo: required

services:
      - docker

go:
- 1.7

install:
    - make go-get

script:
    - make all check lint format-check coverage docker-build-quilt docker-build-tester

after_success:
    - bash <(curl -s https://codecov.io/bash)
    - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
          docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
          docker push quilt/quilt;
          docker push quilt/tester;
      fi

notifications:
  slack:
    secure: shSMMFfAWuY0CFXeN9R9DiaQ4c+tQZlHVitMi9gOc5SfPnnzJfVJnbUoVfQKRjdUTAMo3/D6t5ohcOD9Xl+mfXfuyAa6fF6nnHTL/gE2VavIwo+TXF8Pld8QCZ0C6IQAV8Dl6HIQRCaQB4zBjT3/PKMymxGt59ej4s7s+BPwYPj1ZdHxdv6690Mn/T8ivaH8HZcCs7V5LjkH9s6265Gcy83oKNBKMCZ0nQ4y4Wwn19nztqDry7AWTU7jHFFMbsk0d9sDWEZw2EVt6WikVmiMq032wGapYSNVzViUOKSLDxhahPMgSXjf0PcFOxmx1F9EL1yn5Ra/zdnHIkjfWrlqbiovY5dk6iJm6dE1StmIBDP1P9C4DsOuIJKQOaqT8AGQ439NOqN9TggT5AtEzF378kHdYA/sclMJSKxu4zSsGlSZ+ggzW5WWwqtw2a5IDOmt/+ezIbPuhdVVlJCy4DDGe664eiaawT7dPWbutw29jTc91rEWlhY+/mg80qiIjH/f4wn6vyn9FKDPU5Ofip3llT3R+u03D0FQ6vrav0a0A22z0yhs6iIwlkh9mXnxmt6uy0KGwBMsK1l/lXKJ5odldGIOLhk9sTiCB1BJBslPEsNlBnNwIXU97rvtMn6FPYsYUo6qO5UKglWn6rWOygyyAS5F5dNhq2wR6XdFNOtf83M=
